# -*- coding: utf-8 -*-
"""PythonProgramlamayaCokHizliBirGiris.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10QoppIG5OUrIMdkOdyhuuDRSo1JmmJ0A

# **PYTHON PROGRAMLAMAYA ÇOK HIZLI BİR GİRİŞ**

**ALTUĞ BEYHAN**

http://www.altugbeyhan.com

OnlineGDB: https://www.onlinegdb.com/

Google Colab: https://colab.research.google.com/

Eğer bilgisayarınıza yazılım kurmak isterseniz:

PyCharm: https://www.jetbrains.com/pycharm/download/ (OnlineGDB alternatifi)

Anaconda: https://www.anaconda.com/products/distribution (Google Colab alternatifi)

## Merhaba dünya!

### print() fonksiyonu
"""

#print(Merhaba dünya!)

print("Merhaba dünya!")

print(5)

print(3+4)

print("3+4")

"""Varsayılan değerler

sep: boşluk, end: \n (alt satıra geçiş)
"""

print("altuğ\nbeyhan")

print("altuğ","beyhan","elma","armut")
print("altuğ","beyhan","elma","armut", sep="*")

print("altuğ")
print("beyhan")
print("elma")

print("altuğ", end="*")
print("beyhan", end="*")
print("elma", end="*")

"""### Yorumlama"""

print("altuğ") # bu bir yorumdur
#print("beyhan")
print("elma") # print(3+2)

"""print("altuğ")
print("altuğ")
print("altuğ")
print("altuğ")
print("altuğ")

## Veri Tipleri

### type() fonksiyonu

str (string): yazı

int (integer): tam sayı

float: ondalıklı sayı
"""

print(type("altuğ"))

print(type(5))

print(type(3.14))

print(type(3.0))

"""## Matematiksel İşlemler"""

print(3+2) # toplama işlemi

print(3-2) # çıkarma işlemi

print(3*2) # çarpma işlemi

print(3/2) # bölme işlemi

print(11//4) # 11'in 4'e bölümünden elde edilen bölüm

print(11%4) # 11'in 4'e bölümünden elde edilen kalan (mod 4)

print(3**4) # kuvvet

print(9**(1/2)) # (2). dereceden kök

"""## Değişkenler"""

x = 5 # x adlı değişkene 5 değerini atıyoruz

print(x)

x = x + 1 # x adlı değişkene, onun 1 fazlası atandı

print(x)

y = 3

print(x*y)

isim = "altuğ"
soyisim = "beyhan"

print(isim)
print(soyisim)

print(isim+soyisim)

sayi = 3
print(sayi)
sayi = 5
print(sayi)

sayi = 3 # kodlar yukarıdan aşağıya doğru satır satır okunur
sayi = 5
print(sayi)

"""## Fonksiyonların Tanımlanması

builtin_function_or_method: yerleşik fonksiyon veya metot

function: fonksiyon (yerleşik olmayan, bizim tanımladığımız)
"""

print(type(print))

def merhabaDunya():
    print("Merhaba Dünya!")

merhabaDunya() # (): çağırmak/çalıştırmak

print(type(merhabaDunya))

def topla(x,y): # x,y: argüman (parametre)
    print("Birinci sayı:",x)
    print("İkinci sayı:",y)
    print("Sayıların toplamı:",x+y)

topla(6,12)

"""### Metotlar"""

isim = "aLtuĞ bEyHan" # str sınıfından bir nesne

sayi = 3 # int sınıfından bir nesne

print(isim.capitalize()) # isim nesnesi üzerinde capitalize adlı str'nin bir fonksiyonu (metot) çağırılıyor

print(isim.upper())

print(isim.lower())

"""## Koşullu Durumlar

### if-elif-else

if: eğer

else: aksi halde

elif: else if (2'den fazla durum)

**KOŞULLAR**

eşittir: ==

eşit değildir: !=

küçüktür: <

büyüktür: >

küçük eşittir: <=

büyük eşittir: >=
"""

x = 10

if x == 10:
    print("sayı 10'a eşit")

x = 20

if x == 10:
    print("sayı 10'a eşit")

x = 20

if x == 10:
    print("sayı 10'a eşit")
else:
    print("sayı 10'a eşit değil")

x = 7

if x != 5:
    print("sayı 5'e eşit değil")
else:
    print("sayı 5'e eşit")

sayi = 13

if sayi < 12:
    print("sayı 12'den küçük")

elif sayi == 12:
    print("sayı 12'ye eşit")

else:
    print("sayı 12'den büyük")

"""## Döngüler

### While Döngüsü

while: -iken

while KOŞUL: KOŞUL sağlanıyor iken:
"""

x = 1

while x <= 12:
    print(f"{x}. sınıf") #format print
    x = x + 1 # x'i değiştirmezsek sonsuz döngü olur!

print(x)

"""### For döngüsü"""

listem = ["altuğ",10,"beyhan",20,20,20,"altuğ"]

print(listem)

print(type(listem))

for eleman in listem:
    print(f"şu anda eleman={eleman} alındı")

print(range(10))
print(type(range(10)))

for i in range(10): # 0'dan 10'a kadar (10 dahil değil)
    print(i**2)

print(list(range(10)))

# (1+(1/n))**n dizisinin n= 1, 10, 100, 1000, ... altındaki görüntüleri

for i in range(10):
    n = 10**i
    print(f"n={n} için dizinin terimi = {(1+(1/n))**n}")

"""## Mantıksal İşlemler

bool (Boolean): doğru/yanlış

and (ve), or (veya), not (değil/olumsuz)
"""

print(True)

print(False)

print(type(True))

print(True and True)
print(True and False)
print(False and True)
print(False and False)

print(True or True)
print(True or False)
print(False or True)
print(False or False)

print(not True)
print(not False)

"""## Bu dersten sonrası

Python Türkçe Dokümantasyon: https://docs.python.org/tr/3/tutorial/introduction.html#using-python-as-a-calculator

ChatGPT: https://chat.openai.com/chat/ 

BTK Akademi Eğitimleri:

https://www.btkakademi.gov.tr/portal/course/sifirdan-ileri-seviye-python-programlama-5877

https://www.btkakademi.gov.tr/portal/course/veri-bilimi-icin-python-ve-tensorflow-11705

Turkcell Geleceği Yazanlar Eğitimleri:

https://gelecegiyazanlar.turkcell.com.tr/konu/egitim/python-programlama-101/pythona-giris

https://gelecegiyazanlar.turkcell.com.tr/konu/ileri-python

Global AI Hub Eğitimi:

https://globalaihub.com/courses/introduction-to-python-turkish/
"""

